from __future__ import annotations

import copy
from pathlib import Path
import yaml


REPORT_DIR = Path("/home/ythuang/workspace/bizidea/ideas/20260427084248-atech-physical-ai-hardware")


TRANSLATIONS = {
    "AI hardware prototyping": "AI 硬件原型设计",
    "Manufacturing handoff OS for robotics teams turning AI-generated board concepts into supplier-ready pilot builds.": "面向机器人团队的制造交接 OS，将 AI 生成的板级概念转化为可直接交付供应商的试产方案。",
    "today": "今天",
    "$180M TAM and $33.8M beachhead at 7% CAGR support a real niche, but five mapped competitors keep the market only moderately open.": "$180M 的 TAM 与 $33.8M 的切入市场、7% CAGR 共同支撑了一个真实细分赛道，但已识别的五家竞品使市场开放度仅属中等。",
    "A neutral handoff OS with revision-linked supplier, DFM, and bring-up data is sharper than design tools or manufacturing-tied alternatives.": "一个中立的交接 OS，将供应商、DFM 和 bring-up 数据与版本修订关联起来，相比设计工具或绑定制造方的替代方案更具针对性。",
    "Five staged hires, clear 12-24 month milestones, 75% gross margin, 9.9x LTV/CAC, and 7.2-month payback offset three scaling flags.": "五个分阶段招聘岗位、清晰的 12-24 个月里程碑、75% 毛利率、9.9x LTV/CAC 以及 7.2 个月回本周期，抵消了三项扩张风险信号。",
    "Four same-day signals around Atech's launch, funding, and live waitlist make prototype-to-production handoff a current bottleneck.": "围绕 Atech 上线、融资和实时候补名单的四个当日信号表明，原型到量产的交接正是当下的瓶颈。",
    "Incumbent design tools add similar features": "现有设计工具加入类似功能",
    "Beachhead may be too early-stage to pay": "切入市场可能阶段过早，付费意愿不足",
    "Bad recommendations could create hardware liability": "错误建议可能带来硬件责任风险",
    "Atech turns hardware prototyping into a prompt-driven AI workflow.": "Atech 正将硬件原型设计转变为由提示驱动的 AI 工作流。",
    "Strong startup relevance and opportunity clarity, weaker non-obviousness.": "与创业场景高度相关、机会清晰，但非显性独特性稍弱。",
    "Fresh pre-seed hardware-AI funding plus live product framing makes a clear venture wedge in AI-assisted hardware prototyping; only two credible same-day sources surfaced.": "新近的硬件 AI pre-seed 融资叠加产品已上线的信号，使 AI 辅助硬件原型设计出现了清晰的创业切口；但当天仅出现两条可信来源。",
    "No matching historical slug, event key, URL, or keyword bundle appeared in the index, so this looks new.": "索引中未出现匹配的历史 slug、事件键、URL 或关键词组合，因此这看起来是一个新主题。",
    "Atech says it raised a pre-seed round with participation from Nordic Makers, Emblem, Lovable, Sequoia Scout Fund, and Andreessen Horowitz Scout Fund.": "Atech 表示其已完成一轮 pre-seed 融资，参与方包括 Nordic Makers、Emblem、Lovable、Sequoia Scout Fund 和 Andreessen Horowitz Scout Fund。",
    "The company is building a platform that makes hardware development accessible through natural-language prompting.": "该公司正在打造一个通过自然语言提示降低硬件开发门槛的平台。",
    "CEO Tomas Harmer frames the product as removing one of hardware's highest barriers to entry.": "CEO Tomas Harmer 将该产品定义为消除硬件领域最高进入门槛之一的工具。",
    "The homepage says Atech raised $800K to build the foundational layer of hardware.": "官网称 Atech 已融资 $800K，用于构建硬件领域的基础层。",
    "It describes a chat-based flow that generates a hardware configuration and working code in minutes.": "官网描述了一种基于聊天的流程，可在数分钟内生成硬件配置和可运行代码。",
    "The site includes pre-order and waitlist prompts, indicating an early launch phase.": "网站包含预购和候补名单入口，表明其仍处于早期发布阶段。",
    "Investors are funding prompt-native hardware tooling": "投资人正在为原生提示式硬件工具提供资金",
    "Atech closed a pre-seed round for a natural-language hardware platform, showing investors believe the category is emerging now.": "Atech 为其自然语言硬件平台完成 pre-seed 融资，表明投资人认为这一品类正在形成。",
    "Hardware configuration plus code generation is becoming real": "硬件配置与代码生成正变得切实可行",
    "Atech claims a chat flow can generate both a hardware configuration and working code in minutes, collapsing early design time.": "Atech 宣称其聊天式流程可在数分钟内同时生成硬件配置和可运行代码，大幅压缩前期设计时间。",
    "Barrier-to-entry compression will expand the builder base": "进入门槛下降将扩大开发者基础",
    "Atech explicitly positions its product as removing one of hardware's highest barriers to entry, implying more less-experienced teams will attempt custom hardware.": "Atech 明确将产品定位为消除硬件领域最高进入门槛之一，这意味着会有更多经验较少的团队尝试定制硬件。",
    "Demand is forming before the category is mature": "在品类成熟前，需求已开始形成",
    "The live pre-order and waitlist flow suggests early adopters are already shopping for AI-native hardware workflows before incumbent tooling catches up.": "实时预购和候补名单流程表明，在现有工具追上之前，早期采用者已开始寻找 AI 原生硬件工作流。",
    "Prompt-driven tools can speed up initial hardware concepts, but they do not solve the messy work needed to turn a generated design into a manufacturable pilot build. Seed-stage robotics and industrial-device teams still lose weeks to BOM cleanup, alternates research, DFM feedback, firmware bring-up planning, and supplier quote packaging. That gap causes respins, missed pilot dates, and expensive dependence on consultants just when teams are trying to prove field traction.": "提示驱动工具可以加快最初的硬件概念生成，但并不能解决把生成的设计转化为可制造试产方案所需的繁杂工作。处于种子阶段的机器人与工业设备团队，仍要花费数周处理 BOM 清洗、替代料研究、DFM 反馈、固件 bring-up 规划以及供应商询价资料打包。这一缺口会在团队试图验证现场落地效果时，导致重转板、错过试产节点，并高成本依赖顾问。",
    "Founding electrical engineers and CTOs at seed-to-Series A robotics startups building their first custom control board for pilot deployments": "处于种子轮至 Series A 阶段、正在为试点部署开发首块自定义控制板的机器人初创公司创始电气工程师和 CTO",
    "Embedded systems consultancies helping industrial-device startups move from dev kits to custom boards": "帮助工业设备初创公司从开发板过渡到定制板卡的嵌入式系统咨询公司",
    "CTO or Head of Hardware": "CTO 或硬件负责人",
    "As natural-language tools make hardware concept generation fast, the bottleneck shifts downstream to production handoff, where manufacturability, sourcing risk, and bring-up discipline still live in fragmented tribal knowledge.": "随着自然语言工具让硬件概念生成变得更快，瓶颈会向下游转移到量产交接环节，而可制造性、采购风险和 bring-up 规范仍分散在碎片化的经验知识中。",
    "Robotics and industrial-device startups moving from off-the-shelf dev boards to a first custom PCB for 10-500 pilot units": "从现成开发板过渡到首块定制 PCB、面向 10-500 台试产规模的机器人与工业设备初创公司",
    "An AI handoff layer that ingests requirements, schematics, or prompt-generated configurations and outputs a DFM-checked BOM, approved alternates, firmware bring-up checklist, and CM-ready RFQ package": "一个 AI 交接层，能够接收需求、原理图或提示生成的配置，并输出经过 DFM 检查的 BOM、已批准替代料、固件 bring-up 清单以及可交付给 CM 的 RFQ 包。",
    "Atech's funded launch and live waitlist show prompt-based hardware creation is arriving now, making prototype-to-production handoff the next acute bottleneck.": "Atech 的融资发布与实时候补名单表明，基于提示的硬件创建正在到来，使原型到量产的交接成为下一个尖锐瓶颈。",
    "Start with first-board handoff for startups, then expand into recurring hardware program management, approved component knowledge graphs, supplier performance data, and compliance workflows across robotics, drones, industrial IoT, and OEM design partners.": "先从初创公司的首板交接切入，再扩展到持续性的硬件项目管理、已批准器件知识图谱、供应商绩效数据，以及覆盖机器人、无人机、工业物联网和 OEM 设计合作方的合规工作流。",
    "Teams upload a requirements doc, schematic export, BOM, or AI-generated hardware configuration, and the product converts it into a pilot-build release package. The software flags lifecycle and sourcing risk, recommends alternates, generates manufacturing notes and bring-up tests, and packages quote-ready files for contract manufacturers. It keeps traceability from product intent to component decisions so small teams can explain why a design changed and what must be revalidated. Over time, the system learns from supplier feedback, accepted alternates, and bring-up failures to improve recommendations on every new board revision.": "团队上传需求文档、原理图导出文件、BOM 或 AI 生成的硬件配置后，产品会将其转化为试产发版包。软件会标记生命周期与采购风险、推荐替代料、生成制造说明和 bring-up 测试，并为合约制造商打包可直接询价的文件。它保留从产品意图到元器件决策的可追溯性，使小团队能够解释设计为何变更以及哪些内容需要重新验证。随着时间推移，系统会从供应商反馈、已接受替代料和 bring-up 失败中学习，持续改进每一版新板卡的建议质量。",
    "CTO at a 10-80 person warehouse robotics startup preparing its first 50-200 unit pilot run with only one or two electrical engineers on staff": "一家 10-80 人仓储机器人初创公司的 CTO，团队仅有一到两名电气工程师，正在准备首个 50-200 台的试产批次",
    "The team commits to a pilot deployment and needs to request CM quotes after outgrowing dev-board prototypes": "团队确定进入试点部署后，在开发板原型已无法满足需求的情况下，需要向 CM 发起询价",
    "Manual workflow across Altium or KiCad exports, spreadsheets, distributor portals, CM email threads, and outside EE consultants": "在 Altium 或 KiCad 导出文件、电子表格、分销商门户、CM 邮件往来以及外部 EE 顾问之间手动流转的工作方式",
    "It removes weeks of error-prone release prep and reduces respin risk without requiring the startup to hire a dedicated hardware operations lead": "它可以在不要求初创公司招聘专职硬件运营负责人的情况下，消除数周易出错的发版准备工作，并降低重转板风险。",
    "Annual platform fee per active hardware program plus usage-priced releases for each board revision sent to manufacturing": "按每个活跃硬件项目收取年度平台费，并对每次送交制造的板卡修订按发版次数收费",
    "Seed funding behind Atech suggests prompt-native hardware workflows are becoming credible rather than experimental.": "Atech 获得种子轮融资，表明原生提示式硬件工作流正从实验性概念变为可信方向。",
    "Once hardware configuration and code can be generated in minutes, the slowest remaining step becomes validating and packaging designs for real-world builds.": "一旦硬件配置和代码可以在几分钟内生成，剩余最慢的环节就变成了为真实制造验证并打包设计。",
    "Lower barriers to starting hardware projects will create more first-time teams that need guardrails before sending designs to manufacturers.": "硬件项目启动门槛降低后，会出现更多首次做硬件的团队，他们在把设计发给制造商前需要更多约束与护栏。",
    "Live waitlists indicate buyers are already testing AI-native hardware workflows, creating an opening to own the production handoff layer before incumbents react.": "实时候补名单表明买方已经在测试 AI 原生硬件工作流，这为在现有厂商反应过来前占据量产交接层创造了机会。",
    "This is not a generic CAD copilot that helps draw circuits faster. It owns the prototype-to-production handoff where startups actually burn cash: component risk, manufacturing readiness, RFQ packaging, and firmware bring-up discipline. The defensible data asset is a growing graph of accepted alternates, supplier outcomes, DFM issues, and bring-up failures tied to real board revisions. That feedback loop gets stronger as more designs move through the platform and into manufacturing.": "这不是一个帮助更快画电路的通用 CAD 副驾。它瞄准的是初创公司真正烧钱的原型到量产交接环节：元器件风险、制造就绪度、RFQ 打包以及固件 bring-up 规范。其可防御的数据资产，是一个持续增长的图谱，将已接受替代料、供应商结果、DFM 问题和 bring-up 失败与真实板卡修订关联起来。随着更多设计经过平台并进入制造，这一反馈闭环会越来越强。",
    "From Prompted Design to Pilot Build": "从提示式设计到试产构建",
    """flowchart LR
Buyer[CTO or Founding EE] --> Pain[Prototype is not production-ready]
Pain --> Product[Prototype-to-production OS]
Product --> Outcome[Faster pilot builds with fewer respins]
""": """flowchart LR
Buyer[CTO 或创始 EE] --> Pain[原型尚未达到量产就绪]
Pain --> Product[原型到量产 OS]
Product --> Outcome[更快的试产，且更少重转板]
""",
    "Seed-to-Series A robotics startups building first custom electronics": "正在打造首套定制电子系统的种子轮至 Series A 机器人初创公司",
    "Industrial IoT device startups preparing pilot manufacturing": "准备进入试产制造的工业 IoT 设备初创公司",
    "Embedded systems consultancies supporting early hardware teams": "支持早期硬件团队的嵌入式系统咨询公司",
    "Turn generated or draft hardware designs into CM-ready release packages": "将生成式或草稿级硬件设计转化为可交付给 CM 的发版包",
    "Reduce respins through BOM risk detection and bring-up planning": "通过 BOM 风险识别和 bring-up 规划减少重转板",
    "Compress time from concept to quoted pilot build": "缩短从概念到试产报价的时间",
    "Founder-led outbound to robotics startups": "由创始人主导面向机器人初创公司的外拓",
    "Partnerships with contract manufacturers and design consultancies": "与合约制造商和设计咨询公司建立合作伙伴关系",
    "Hardware accelerator and incubator networks": "硬件加速器和孵化器网络",
    "High-touch onboarding on first board program": "在首个板卡项目上提供高接触式导入服务",
    "Design review and release success check-ins": "设计评审与发版成功复盘",
    "Template libraries and guided workflows for repeat releases": "用于重复发版的模板库与引导式工作流",
    "Annual software subscriptions": "年度软件订阅",
    "Per-release fees for manufacturing handoff packages": "按次收取制造交接包费用",
    "Premium supplier and compliance workflow modules": "高级供应商与合规工作流模块",
    "Component and alternate knowledge graph": "元器件与替代料知识图谱",
    "DFM and bring-up workflow engine": "DFM 与 bring-up 工作流引擎",
    "Supplier and CM integration relationships": "供应商与 CM 集成关系",
    "Normalize design inputs and BOMs": "标准化设计输入和 BOM",
    "Generate and validate release packages": "生成并验证发版包",
    "Capture outcome data from supplier feedback and board revisions": "捕获来自供应商反馈和板卡修订的结果数据",
    "Contract manufacturers": "合约制造商",
    "Component distributors": "元器件分销商",
    "Hardware design consultancies": "硬件设计咨询公司",
    "Engineering for design parsers and workflow automation": "用于设计解析器和工作流自动化的工程投入",
    "Hardware domain experts for validation templates": "负责验证模板的硬件领域专家",
    "Customer success for first-program onboarding": "用于首个项目导入的客户成功投入",
    "When our team is moving from a dev-board prototype to a custom pilot board, help our CTO package a manufacturable release, so they can get quotes quickly and avoid a costly respin.": "当我们的团队从开发板原型转向定制试产板时，帮助 CTO 打包出可制造的发版版本，以便更快获取报价并避免代价高昂的重转板。",
    "Manual spreadsheets, CM back-and-forth, and consultant review": "手工表格、与 CM 反复沟通以及顾问评审",
    "Days from design freeze to first acceptable CM quote and first-pass bring-up success": "从设计冻结到首个可接受 CM 报价，以及首次 bring-up 成功的天数",
    "When a generated or draft BOM contains risky parts, help the founding EE find safe alternates and document changes, so they can keep the pilot schedule on track.": "当生成式或草稿版 BOM 包含高风险器件时，帮助创始 EE 找到安全的替代料并记录变更，从而保证试产进度不被打乱。",
    "Distributor searches and ad hoc internal review": "分销商检索和临时性的内部审查",
    "Number of sourcing blockers resolved without changing the deployment timeline": "在不改变部署时间线的前提下解决的采购阻塞数量",
    "Two same-day verified sources show both investor validation and a live product claim for prompt-driven hardware generation.": "两条当天验证来源同时证明了投资人认可，以及提示驱动硬件生成产品已经上线的主张。",
    "First-board manufacturing mistakes are expensive, schedule-critical, and painful for small hardware teams.": "首板制造错误成本高、对进度影响关键，并且会给小型硬件团队带来巨大痛苦。",
    "Prototype-to-production handoff is a narrow workflow with clear outputs, buyers, and switching moments.": "原型到量产交接是一个边界清晰的工作流，拥有明确的输出物、买方和切换时点。",
    "Outcome data from alternates, DFM findings, and supplier responses can compound into a hard-to-replicate workflow graph.": "替代料结果、DFM 发现和供应商反馈形成的结果数据，可以逐步沉淀为难以复制的工作流图谱。",
    "The beachhead is narrow, but the workflow can expand into the operating system for recurring hardware programs across several large device categories.": "切入市场虽然较窄，但该工作流可以扩展为多个大型设备品类中重复性硬件项目的操作系统。",
    "PCB and PLM vendors could extend upward from design authoring into manufacturing handoff.": "PCB 和 PLM 厂商可能从设计创作环节向上延伸至制造交接环节。",
    "Own the cross-tool workflow and accumulate proprietary supplier outcome data that generic design suites do not capture.": "占据跨工具工作流，并积累通用设计套件无法捕获的专有供应商结果数据。",
    "Small startups may love the workflow but hesitate to buy until they are close to production.": "小型初创公司可能喜欢这套工作流，但在接近量产前仍会犹豫是否购买。",
    "Sell at the exact pilot-build trigger and package ROI around avoided respins, consultant spend, and time-to-quote savings.": "在试产触发点精准销售，并围绕避免重转板、减少顾问支出和缩短报价时间来包装 ROI。",
    "Incorrect alternates or release guidance could cause failed boards and trust loss.": "错误的替代料或发版指导可能导致板卡失败并损害信任。",
    "Start with human-in-the-loop approvals, clear confidence scoring, and a narrow scope around reviewable manufacturing artifacts rather than autonomous signoff.": "先从人机协同审批、清晰的置信度评分以及围绕可审查制造工件的狭窄范围切入，而不是追求自动签核。",

    "This company should be built as a manufacturer-agnostic prototype-to-production OS for seed-to-Series A hardware teams that are leaving dev boards and preparing their first serious pilot build. The immediate customer is a 10-80 person robotics or industrial-device startup with one or two electrical engineers that suddenly needs a CM-ready release package, alternate parts, and bring-up discipline without hiring a hardware operations team. The core product is not another CAD copilot; it is a release-control workflow that ingests partial design artifacts and outputs a traceable pilot-build package with BOM health, approved alternates, RFQ files, assembly notes, and bring-up tests. The beachhead is attractive because the buying trigger is concrete and deadline-driven: the moment a team commits to a 10-500 unit pilot deployment and must request real CM quotes. Research supports the market timing, category tailwinds, and competitive whitespace, but it does not yet prove trust in machine-generated alternates or software-only willingness to pay, so those remain the first board-level assumptions to test. The company wins if it becomes the neutral system of record between mixed design tools and mixed manufacturers while capturing outcome data on accepted alternates, DFM issues, quote readiness, and bring-up failures. It should deliberately avoid broad CAD authoring, full PLM scope, or captive manufacturing economics until it has repeatable proof that first-board handoff is a wedge buyers will pay for.": "这家公司应被打造为一个与制造商无关的原型到量产 OS，面向正在脱离开发板、准备首次真正试产的种子轮至 Series A 硬件团队。眼前的客户是 10-80 人规模的机器人或工业设备初创公司，团队只有一到两名电气工程师，却突然需要一个可交付给 CM 的发版包、替代料方案和 bring-up 规范，而不想招聘硬件运营团队。核心产品不应是另一个 CAD 副驾，而应是一个发版控制工作流：输入不完整的设计工件，输出可追溯的试产发版包，其中包括 BOM 健康度、已批准替代料、RFQ 文件、装配说明和 bring-up 测试。这个切入市场具有吸引力，因为购买触发点非常明确且受截止时间驱动：当团队承诺开展 10-500 台的试点部署，并且必须发起真实 CM 询价的那一刻。研究支持该市场时机、品类顺风以及竞争留白，但尚未证明客户会信任机器生成的替代料建议，也尚未证明其愿意为纯软件付费，因此这些仍是最先需要验证的板级假设。若公司能在混合设计工具与混合制造商之间成为中立的系统记录层，同时沉淀已接受替代料、DFM 问题、报价就绪度和 bring-up 失败的结果数据，它就有机会获胜。在获得可重复验证、证明“首板交接”是买方愿意付费的切口之前，公司应有意识地避免扩展到广义 CAD 创作、完整 PLM 范围或自营制造经济模式。",
    "Seed-stage robotics and industrial-device teams can now generate first-pass hardware concepts faster, but still lose weeks turning those artifacts into manufacturable pilot-build releases.": "处于种子阶段的机器人和工业设备团队现在可以更快生成首版硬件概念，但仍要花费数周才能把这些工件变成可制造的试产发版版本。",
    "First-board workflows remain fragmented across Altium or KiCad exports, spreadsheets, distributor portals, CM email threads, and consultant reviews, which creates version errors, sourcing churn, and slow quote cycles.": "首板工作流仍然分散在 Altium 或 KiCad 导出文件、电子表格、分销商门户、CM 邮件往来和顾问审查中，导致版本错误、采购反复和报价周期缓慢。",
    "A single bad alternate, missing note, or incomplete bring-up plan can cause a respin, pilot delay, or failed first article at the exact moment a startup needs field proof.": "一个错误的替代料、一条缺失的说明或一个不完整的 bring-up 计划，都可能在初创公司最需要现场验证的时刻造成重转板、试产延期或首件失败。",
    "Ingest requirements docs, schematic exports, BOMs, Gerbers, or prompt-generated hardware configurations and convert them into a CM-ready release package.": "接收需求文档、原理图导出、BOM、Gerber 或提示生成的硬件配置，并将其转化为可交付给 CM 的发版包。",
    "Flag lifecycle and sourcing risk, recommend reviewable alternates, generate manufacturing notes, and create firmware bring-up and test checklists tied to each board revision.": "标记生命周期和采购风险，推荐可审查的替代料，生成制造说明，并为每个板卡修订创建固件 bring-up 与测试清单。",
    "Maintain traceability across design intent, component changes, supplier feedback, and release approvals so small teams can explain what changed and what must be revalidated.": "在设计意图、元器件变更、供应商反馈和发版审批之间保持可追溯性，让小团队可以解释发生了什么变化，以及哪些内容必须重新验证。",
    "The product is aimed at the handoff bottleneck where hardware startups burn schedule and cash, not at generic design authoring where incumbents are strongest.": "产品瞄准的是硬件初创公司真正消耗时间和现金的交接瓶颈，而不是现有厂商最强的通用设计创作环节。",
    "The first customer has an urgent, deadline-based trigger and can measure ROI in time-to-quote, avoided consultant spend, and reduced respin risk.": "首批客户具有紧迫且受截止时间驱动的触发点，并能从报价时间缩短、减少顾问支出和降低重转板风险上衡量 ROI。",
    "A supplier-agnostic workflow fits mixed-tool and mixed-manufacturer environments better than CM-tied platforms or broad ECAD suites.": "相比绑定 CM 的平台或宽泛的 ECAD 套件，一个与供应商无关的工作流更适合混合工具、混合制造商环境。",
    "The compounding asset is a revision-linked graph of accepted alternates, DFM findings, quote outcomes, and bring-up failures that small teams cannot build alone.": "可复利积累的资产，是一个与修订版本关联的图谱，覆盖已接受替代料、DFM 发现、报价结果和 bring-up 失败，而这不是小团队单独能够构建的。",
    "Seed-to-Series A robotics and industrial-device startups in North America and Western Europe moving from dev boards to a first custom PCB for a 10-500 unit pilot run.": "位于北美和西欧、正从开发板过渡到首块定制 PCB、面向 10-500 台试产批次的种子轮至 Series A 机器人与工业设备初创公司。",
    "This wedge has a clear user, a known economic buyer, a painful deadline, and a narrow deliverable. It creates faster proof than a broader hardware platform because the company can win one high-value workflow before expanding into adjacent program management or compliance work.": "这个切口拥有明确用户、清晰的经济买方、痛苦的截止时间和边界明确的交付物。与更宽泛的硬件平台相比，它能更快验证，因为公司可以先拿下一个高价值工作流，再扩展到相邻的项目管理或合规工作。",
    "Start with concierge-assisted release packaging to learn the artifact gaps and trust thresholds, then productize BOM risk, RFQ packet generation, and bring-up traceability, and only later add deeper supplier integrations and compliance modules once outcome data exists. This ordering keeps product scope, GTM motion, and hiring aligned around the same first-board release event.": "先用礼宾式辅助发版打包来学习工件缺口和信任阈值，再将 BOM 风险、RFQ 包生成和 bring-up 可追溯性产品化，只有在拥有结果数据后才进一步加入更深的供应商集成和合规模块。这样的顺序能让产品范围、GTM 动作和招聘节奏都围绕同一个首板发版事件保持一致。",
    "Full PCB authoring or schematic-generation tooling": "完整的 PCB 创作或原理图生成工具",
    "Mechanical CAD, enclosure workflows, or full mechatronics program management": "机械 CAD、外壳工作流或完整的机电一体化项目管理",
    "Captive manufacturing marketplace economics": "自营制造平台的交易型经济模式",
    "Broad enterprise PLM or ERP replacement": "广义企业级 PLM 或 ERP 替代方案",
    "$180.0M estimated global annual software and release-usage spend for electronics teams with recurring board-release handoff pain.": "估算全球每年约 $180.0M 的软件与按次发版使用支出，面向持续存在板卡发版交接痛点的电子团队。",
    "$33.8M estimated annual spend across North America and Europe seed-to-Series A robotics, industrial-device, and embedded consultancy accounts.": "估算北美和欧洲的种子轮至 Series A 机器人、工业设备及嵌入式咨询客户，每年总支出约为 $33.8M。",
    "$1.6M reachable year-3 revenue equivalent at roughly 65 paying accounts around a $25k blended ACV.": "按约 65 个付费客户、约 $25k 混合 ACV 计算，第 3 年可触达的收入规模约为 $1.6M。",
    "Robotics and industrial-device startups preparing a first custom control board for pilot deployments": "正在为试点部署准备首块定制控制板的机器人与工业设备初创公司",
    "Embedded systems consultancies managing repeated first-board releases for startup clients": "为初创客户管理重复性首板发版的嵌入式系统咨询公司",
    "The founding EE or embedded lead usually drives evaluation once the team commits to a pilot deployment or requests its first serious CM quotes. The CTO or Head of Hardware signs when the software is clearly tied to fewer release errors, faster quotes, and less need for outside hardware-ops help.": "一旦团队决定进行试点部署或首次发起正式 CM 询价，通常由创始 EE 或嵌入式负责人主导评估。当软件能够清晰带来更少的发版错误、更快的报价以及更少对外部硬件运营帮助的依赖时，CTO 或硬件负责人会签字购买。",
    "Concierge-assisted release OS that ingests BOMs and design exports, produces BOM risk reports, suggests reviewable alternates, builds a standardized RFQ packet, and generates a bring-up checklist with revision traceability. Human approval stays in the loop for alternates, DFM flags, and packet signoff.": "一个礼宾式辅助的发版 OS，接收 BOM 和设计导出文件，生成 BOM 风险报告、提出可审查的替代料建议、构建标准化 RFQ 包，并生成带修订可追溯性的 bring-up 清单。替代料、DFM 标记和包签核都保留人工审批。",
    "Productize the first release workflow with parsers for KiCad, Altium exports, and spreadsheet BOMs, plus a release workspace that tracks issues, approvals, quote packets, and CM feedback.": "将首个发版工作流产品化，支持 KiCad、Altium 导出和电子表格 BOM 解析，并提供一个可追踪问题、审批、报价包和 CM 反馈的发版工作台。",
    "Add revision-to-revision change intelligence, confidence scoring on alternate recommendations, reusable bring-up templates, and role-based collaboration for startups plus consultancy partners.": "加入跨修订版本的变更智能、替代料建议的置信度评分、可复用的 bring-up 模板，以及面向初创公司和咨询伙伴的基于角色协作能力。",
    "Expand into a multi-program hardware operations layer with supplier performance history, certification-readiness checklists, and system-of-record integrations into PLM, part-risk, and procurement tools.": "扩展为多项目硬件运营层，增加供应商绩效历史、认证就绪检查清单，以及与 PLM、器件风险和采购工具的系统记录层集成。",
    "Customers will trust software-assisted recommendations if the workflow is reviewable, traceable, and launched with domain-expert oversight.": "如果工作流可审查、可追溯，并在领域专家监督下上线，客户就会信任软件辅助建议。",
    "The most valuable wedge artifact will be the combined release packet rather than a single point tool for BOM alternates or checklists alone.": "最有价值的切入工件将是组合式发版包，而不是只做 BOM 替代料或清单的单点工具。",
    "Outcome data from CMs and consultancies can be captured consistently enough to form a defensible recommendation engine.": "来自 CM 和咨询公司的结果数据可以被足够一致地采集，从而形成有防御力的推荐引擎。",
    "Sell the product as the fastest path from prototype artifacts to a supplier-ready pilot release for startup hardware teams facing their first custom-board manufacturing event.": "将产品定位为：帮助首次面对定制板制造事件的初创硬件团队，以最快速度从原型工件走向供应商就绪的试产发版。",
    "Founder-led outbound into robotics and industrial-device startups at the dev-board-to-custom-board transition": "在开发板向定制板过渡阶段，由创始人主导面向机器人和工业设备初创公司的外拓",
    "Referral partnerships with contract manufacturers and embedded design consultancies": "与合约制造商和嵌入式设计咨询公司建立转介绍合作",
    "Technical content on BOM risk, DFM, release control, and certification-readiness for early hardware teams": "围绕 BOM 风险、DFM、发版控制和认证就绪度，为早期硬件团队输出技术内容",
    "Lead to qualified pilot 20-30%, qualified pilot to paid pilot 40-50%, paid pilot to annual production contract 50%+, first contract to second program expansion 60%+.": "线索到合格试点 20-30%，合格试点到付费试点 40-50%，付费试点到年度量产合同 50% 以上，首份合同到第二项目扩展 60% 以上。",
    "Annual platform subscription per active hardware program with an included release workspace, plus usage-priced releases for each board revision sent to manufacturing. Start with paid pilots in the $8k-$15k range, then convert successful accounts into $20k-$35k annual contracts once the first production-bound release is completed.": "按每个活跃硬件项目收取年度平台订阅费，包含发版工作台；每次送交制造的板卡修订按发版次数计费。先以 $8k-$15k 的付费试点切入，待首个面向量产的发版完成后，再将成功客户转为 $20k-$35k 的年度合同。",
    "Annual software subscription per active hardware program": "按每个活跃硬件项目收取年度软件订阅费",
    "Usage fees for each manufacturing release package or major revision": "每个制造发版包或重大修订收取按次使用费",
    "Premium modules for supplier performance intelligence, compliance readiness, and advanced audit trails": "用于供应商绩效洞察、合规就绪和高级审计追踪的高级模块",
    "Active hardware program with priced release events tied to board revisions": "与板卡修订绑定、按发版事件计价的活跃硬件项目",
    "Additional board programs inside the same startup": "同一初创公司内部新增板卡项目",
    "Consultancy accounts managing multiple client releases": "管理多个客户发版的咨询公司账户",
    "Supplier intelligence and compliance modules once trust is established": "在建立信任后追加供应商洞察与合规模块",
    "Number of production-bound board releases completed through the platform without a preventable handoff defect": "通过平台完成、且未出现可避免交接缺陷的面向量产板卡发版数量",
    "Days from design freeze to first acceptable CM quote": "从设计冻结到首个可接受 CM 报价的天数",
    "Percentage of flagged BOM risks resolved before quote submission": "在报价提交前已解决的已标记 BOM 风险占比",
    "CM acceptance rate of recommended alternates": "CM 对推荐替代料的接受率",
    "Pilot-to-annual conversion rate": "试点转年度合同的转化率",
    "Second release adoption within the same account": "同一账户内第二次发版的采用率",
    "Revision-linked graph of accepted alternates and rejected alternates by supplier context": "按供应商上下文关联的已接受与被拒绝替代料修订图谱",
    "Structured dataset of DFM defects, packet completeness issues, and quote outcomes across mixed CMs": "跨不同 CM 的 DFM 缺陷、资料包完整性问题和报价结果结构化数据集",
    "Bring-up and first-article failure knowledge tied to board revision history": "与板卡修订历史绑定的 bring-up 与首件失败知识",
    "Trust layer built through auditable approvals and mixed-tool interoperability": "通过可审计审批和跨工具互操作性建立的信任层",
    "Fewer than 3 of the first 10 design partners agree to pay for a release workflow before shipping volume production": "首批 10 个设计合作伙伴中，少于 3 个愿意在批量出货前为发版工作流付费",
    "CM acceptance of recommended alternates stays below 70% after 20 live release packets": "经过 20 个真实发版包后，CM 对推荐替代料的接受率仍低于 70%",
    "Median time-to-quote improvement remains below 30% versus the customer's manual baseline after 6 paid pilots": "完成 6 个付费试点后，相比客户手工基线，报价时间缩短的中位数仍低于 30%",
    """flowchart LR
Wedge[First custom PCB pilot release] --> MVP[Release OS for BOM risk and RFQ packets]
MVP --> Proof[Faster quotes fewer handoff errors]
Proof --> Expansion[Multi-program hardware operations layer]
""": """flowchart LR
Wedge[首块定制 PCB 试产发版] --> MVP[面向 BOM 风险与 RFQ 包的发版 OS]
MVP --> Proof[更快报价，更少交接错误]
Proof --> Expansion[多项目硬件运营层]
""",
    "Watch": "观察",
    "Strong workflow wedge and credible timing, but customer trust and software willingness to pay are still unproven.": "工作流切口强、时机可信，但客户信任和纯软件付费意愿仍未被证明。",
    "The company targets a narrow, deadline-driven handoff problem that incumbents cover only partially and that gets more painful as AI lowers the cost of creating hardware concepts.": "公司瞄准的是一个狭窄且受截止时间驱动的交接问题，现有厂商仅部分覆盖，而且随着 AI 降低硬件概念生成成本，这一痛点会更强。",
    "Small hardware teams may still default to consultants, spreadsheets, or CM help unless the product proves materially better outcomes on live pilot releases.": "如果产品无法在真实试产发版中证明结果显著更好，小型硬件团队仍可能默认选择顾问、表格或 CM 支援。",
    "The next proof point is 5-10 paid or deeply committed design-partner releases showing faster CM quoting and high acceptance of software-assisted alternates.": "下一个关键证明点是 5-10 个付费或高度承诺的设计合作伙伴发版案例，能够展示更快的 CM 报价和软件辅助替代料的高接受率。",
    "CTO at a warehouse robotics startup preparing its first custom control board": "正在准备首块定制控制板的仓储机器人初创公司 CTO",
    "10-80 person company with one or two EEs moving from dev-board prototypes to a 50-200 unit pilot deployment under deadline pressure.": "一家 10-80 人规模、仅有一到两名 EE 的公司，正在截止时间压力下从开发板原型转向 50-200 台的试点部署。",
    "The team commits to a pilot deployment and must request serious CM quotes while cleaning up a prototype BOM and release packet.": "团队决定进入试点部署，同时必须在清理原型 BOM 和发版包的过程中发起正式 CM 询价。",
    "$8k-$15k paid pilot for one release workflow, converting to a $20k-$35k annual contract when the team runs repeated board revisions or a second hardware program.": "针对一次发版工作流的 $8k-$15k 付费试点；当团队开始进行重复板卡修订或第二个硬件项目时，转化为 $20k-$35k 的年度合同。",
    "At least half of interviewed ICP teams rank release packaging and BOM risk as a top-three blocker at the first pilot-build stage.": "至少一半受访 ICP 团队将发版打包和 BOM 风险列为首次试产阶段的前三大阻碍之一。",
    "Five of the first ten design partners pay for the workflow before their first scaled production order.": "首批 10 个设计合作伙伴中有 5 个会在首次规模化生产订单前为该工作流付费。",
    "Recommended alternates are accepted by the customer's CM or sourcing lead in at least 80% of approved cases.": "在已批准案例中，推荐替代料至少有 80% 会被客户的 CM 或采购负责人接受。",
    "Median time from design freeze to first acceptable CM quote falls by at least 50% versus each account's prior manual process.": "从设计冻结到首个可接受 CM 报价的中位时间，相比各账户此前的手工流程至少下降 50%。",
    "At least 30% of closed accounts expand to a second release or second program within 12 months.": "至少 30% 的成交账户会在 12 个月内扩展到第二次发版或第二个项目。",
    "Which artifact creates the most urgent budget pull at purchase time, BOM alternates, RFQ packet generation, or bring-up traceability?": "在购买时，哪个工件最能触发紧迫预算：BOM 替代料、RFQ 包生成，还是 bring-up 可追溯性？",
    "How often do startups trust software-generated alternates without consultant review, and what evidence threshold changes that behavior?": "初创公司在没有顾问审查的情况下，会多大程度信任软件生成的替代料？什么证据门槛会改变这种行为？",
    "Can CM and consultancy partners become repeatable channels without cannibalization concerns?": "CM 和咨询伙伴能否在不担心收入被蚕食的前提下，成为可重复的渠道？",
    "How much of the early revenue mix must be service-assisted to close first contracts?": "为了拿下首批合同，早期收入结构中需要多大比例依赖服务辅助？",
    "What data rights and security controls are required before startups will upload live design artifacts?": "在初创公司愿意上传真实设计工件前，需要满足哪些数据权利和安全控制要求？",
    "Customers may not trust machine-generated alternates or DFM flags enough to use them in live release packets.": "客户可能不会足够信任机器生成的替代料或 DFM 标记，从而不愿在真实发版包中使用。",
    "Design partners repeatedly export recommendations into manual review workflows and refuse to send generated packets to CMs.": "设计合作伙伴反复将建议导出到手工审查流程中，并拒绝把生成的资料包发送给 CM。",
    "Keep experts in the loop, expose evidence and confidence scores, and start with reviewable artifacts rather than autonomous signoff.": "让专家持续参与，展示证据和置信度评分，并从可审查工件而非自主签核开始。",
    "The beachhead may value service-heavy support more than software subscriptions.": "切入市场可能更重视重服务支持，而不是软件订阅。",
    "Early deals close only when bundled with significant manual engineering work and fail to convert into recurring software contracts.": "早期交易只有在捆绑大量人工工程工作时才能成交，并且无法转化为持续性软件合同。",
    "Price paid pilots explicitly, separate service scope from software scope, and productize only the most repeated tasks.": "明确给付费试点定价，将服务范围与软件范围拆分，并只将重复度最高的任务产品化。",
    "Incumbent ECAD or manufacturing platforms could bundle overlapping handoff features.": "现有 ECAD 或制造平台可能会打包提供重叠的交接功能。",
    "Prospects say Altium or a CM portal now covers release packaging, alternates, and collaboration well enough to stop evaluation.": "潜在客户表示，Altium 或某个 CM 门户已足以覆盖发版打包、替代料和协作，因此停止评估。",
    "Stay supplier-agnostic, support mixed tools, and build proprietary outcome data across suppliers that suites cannot match quickly.": "保持与供应商无关、支持混合工具，并构建套件型产品无法快速复制的跨供应商专有结果数据。",
    "Data quality and interoperability gaps could make recommendations unreliable.": "数据质量和互操作性缺口可能导致建议不可靠。",
    "Parser failure rates or unresolved BOM normalization issues remain above 10% across early pilot inputs.": "在早期试点输入中，解析失败率或未解决的 BOM 标准化问题持续高于 10%。",
    "Narrow the initial supported inputs, invest in normalization pipelines, and validate every release against human-reviewed ground truth.": "缩小初始支持输入范围，投入标准化处理链路，并让每次发版都对照人工审查的真实基准进行验证。",
    "Security, export-control, or compliance requirements could slow adoption in sensitive hardware categories.": "安全、出口管制或合规要求可能会减缓敏感硬件类别中的采用速度。",
    "Prospects block pilots due to cloud-hosting, permissions, or data residency objections before technical evaluation begins.": "潜在客户会在技术评估开始前，因云托管、权限或数据驻留问题而阻止试点启动。",
    "Start with lower-sensitivity customers, build auditable access controls early, and define clear boundaries on controlled design data.": "先从敏感度较低的客户切入，及早建立可审计访问控制，并明确受控设计数据的边界。",
    "The first economic wedge is the pilot-release event, not upstream concept generation.": "第一个经济性切口是试产发版事件，而不是上游概念生成。",
    "Interview 15 ICP teams and map the last custom-board release process to confirm budget appears when CM quoting and BOM cleanup begin.": "访谈 15 个 ICP 团队，并梳理其最近一次定制板发版流程，以确认预算是否在 CM 询价和 BOM 清洗开始时出现。",
    "If false, reposition toward upstream design generation or a consultancy-led service instead of release-control software.": "如果不成立，就应转向上游设计生成或咨询主导的服务模式，而不是发版控制软件。",
    "Customers will pay software-first pricing if the workflow removes enough manual NPI coordination.": "如果该工作流能消除足够多的手工 NPI 协调，客户就会接受以软件为主的定价。",
    "Close at least 3 paid pilots at stated pricing before offering annual contracts and compare win rates against service-assisted offers.": "在提供年度合同前，先按既定价格完成至少 3 个付费试点，并与服务辅助型报价的赢单率进行比较。",
    "If false, the company must adopt a services-led entry motion and lower near-term software gross margin expectations.": "如果不成立，公司就必须采用服务主导的切入方式，并下调短期软件毛利率预期。",
    "Mixed-tool interoperability across KiCad, Altium exports, Gerbers, and spreadsheets is necessary for the beachhead.": "在 KiCad、Altium 导出、Gerber 和电子表格之间实现混合工具互操作性，是切入市场的必要条件。",
    "Collect 20 recent customer release packets and quantify the artifact mix and parser coverage required to support 80% of them.": "收集 20 份近期客户发版包，并量化支持其中 80% 所需的工件组合和解析覆盖率。",
    "If false, the product can narrow to one dominant toolchain and reduce engineering scope.": "如果不成立，产品可以收缩到单一主导工具链，并减少工程范围。",
    "Outcome data from CMs and consultancies can be captured in a structured way that improves recommendations over time.": "来自 CM 和咨询公司的结果数据可以被结构化采集，并随时间持续提升建议质量。",
    "Run 10 concierge releases and measure whether supplier responses, accepted alternates, and DFM findings can be normalized with minimal manual cleanup.": "执行 10 次礼宾式发版，衡量供应商反馈、已接受替代料和 DFM 发现是否可以在最少人工清洗下实现标准化。",
    "If false, the moat shifts from data network effects to workflow UX and the long-term defensibility weakens.": "如果不成立，护城河就会从数据网络效应转向工作流 UX，长期防御力也会减弱。",
    "North America and Western Europe provide enough concentrated demand for the first 24 months.": "北美和西欧在前 24 个月内可以提供足够集中的需求。",
    "Build a target account list of 200 startups and 50 consultancies in those geographies and verify reachable pipeline coverage through outbound and partner intros.": "在这些地区建立包含 200 家初创公司和 50 家咨询公司的目标账户名单，并通过外拓和合作伙伴引荐验证可触达管道覆盖。",
    "If false, the company must broaden geography earlier and invest sooner in Asia-oriented sourcing workflows.": "如果不成立，公司就必须更早扩展地域范围，并更早投入面向亚洲供应链的工作流。",
    "0-90 days": "0-90 天",
    "Concierge 10 release-package teardowns with robotics and industrial-device startups.": "与机器人和工业设备初创公司开展 10 次礼宾式发版包拆解。",
    "The highest-value wedge is the combined release packet, not a single-feature tool.": "最高价值的切口是组合式发版包，而不是单一功能工具。",
    "At least 7 of 10 teams identify RFQ packet assembly plus BOM cleanup as a critical path pain and share their latest release artifacts.": "至少 10 个团队中的 7 个会将 RFQ 包组装加 BOM 清洗视为关键路径痛点，并愿意分享其最新发版工件。",
    "Founder CEO": "创始人 CEO",
    "Run 5 live alternate-part and DFM review pilots with CM or consultancy partners.": "与 CM 或咨询伙伴开展 5 次真实的替代料与 DFM 审查试点。",
    "Reviewable software-assisted recommendations can reach trust thresholds for real quote submission.": "可审查的软件辅助建议可以达到真实报价提交所需的信任阈值。",
    "CM or consultancy reviewers approve at least 80% of surfaced issues or alternates after human review.": "在人工复核后，CM 或咨询审查方会批准至少 80% 被识别出的问题或替代料。",
    "Founder hardware lead": "创始硬件负责人",
    "90-180 days": "90-180 天",
    "Convert concierge pilots into paid release engagements at the proposed pilot price point.": "按提议的试点价格，将礼宾式试点转化为付费发版项目。",
    "Startups will pay before full product maturity if ROI is framed around time-to-quote and respin avoidance.": "如果围绕报价时间和避免重转板来包装 ROI，即使产品尚未完全成熟，初创公司也会付费。",
    "Close 3 paid pilots with gross retention through release completion.": "完成 3 个付费试点，并在发版完成前保持总留存。",
    "Launch two referral partnerships with one CM and one embedded consultancy.": "与 1 家 CM 和 1 家嵌入式咨询公司建立两项转介绍合作。",
    "Channel partners can source better-timed opportunities than pure cold outbound.": "渠道合作方能带来时点更精准的机会，优于纯冷启动外拓。",
    "Generate 6 qualified opportunities and 2 paid pilots from partner referrals.": "通过合作伙伴转介绍获得 6 个合格机会和 2 个付费试点。",
    "6-12 months": "6-12 个月",
    "Ship parser and workflow support for the three most common customer artifact combinations.": "为最常见的三种客户工件组合上线解析器和工作流支持。",
    "Covering the dominant artifact patterns will support most pilot accounts without custom implementation work.": "覆盖主流工件模式后，大多数试点账户都可在无需定制实施的情况下得到支持。",
    "80% of inbound pilot opportunities can be onboarded in under one week with no bespoke engineering.": "80% 的流入试点机会可在一周内完成导入，且无需定制工程支持。",
    "Head of product": "产品负责人",
    "12-18 months": "12-18 个月",
    "Test multi-program expansion and annual renewals with early adopters.": "与早期采用者测试多项目扩展和年度续约。",
    "Once one release succeeds, the account will standardize subsequent board revisions through the platform.": "一旦一次发版成功，账户就会通过平台标准化后续板卡修订。",
    "At least 4 accounts run a second release or second hardware program through the product within 12 months of the first contract.": "至少 4 个账户会在首份合同后的 12 个月内，通过产品完成第二次发版或第二个硬件项目。",
    "Customer success lead": "客户成功负责人",
    "Standardize intake around BOMs, design exports, RFQ artifacts, and bring-up notes so every pilot produces reusable structured data.": "围绕 BOM、设计导出、RFQ 工件和 bring-up 说明实现标准化接入，让每次试点都能产出可复用的结构化数据。",
    "Integrate part-risk and lifecycle intelligence from third-party data providers rather than building raw component coverage from scratch.": "接入第三方数据提供商的器件风险和生命周期洞察，而不是从零开始构建原始器件覆盖。",
    "Maintain a human review queue for alternates, DFM flags, and release completeness until measured accuracy is consistently high.": "在测得准确率持续达到高水平前，对替代料、DFM 标记和发版完整性保留人工审核队列。",
    "Build security controls, permissions, and audit trails early because hardware design data sensitivity can block adoption.": "尽早建设安全控制、权限与审计追踪，因为硬件设计数据的敏感性会阻碍采用。",
    "Use CMs and consultancies as feedback partners, but keep the product neutral across manufacturers to preserve customer trust.": "将 CM 和咨询公司作为反馈伙伴，但在制造商之间保持产品中立，以维护客户信任。",
    "Founding eng": "创始工程师",
    "Month 0": "第 0 个月",
    "Needed immediately to build design parsers, revision tracking, and the release workspace around real customer artifacts.": "需要立即到位，以围绕真实客户工件构建设计解析器、修订跟踪和发版工作台。",
    "Founding product and hardware operations lead": "创始产品与硬件运营负责人",
    "Must translate messy NPI and release workflows into product requirements and run early concierge pilots credibly.": "必须把复杂的 NPI 和发版工作流转化为产品需求，并可信地运行早期礼宾式试点。",
    "Applied data and workflow engineer": "应用数据与工作流工程师",
    "Month 3": "第 3 个月",
    "Required once pilots begin to normalize BOM data, confidence scoring, and feedback capture from suppliers.": "当试点开始后，需要负责 BOM 数据标准化、置信度评分和供应商反馈采集。",
    "Solutions engineer": "解决方案工程师",
    "Month 6": "第 6 个月",
    "Supports onboarding, artifact cleanup, and customer trust during the transition from concierge work to repeatable product.": "在从礼宾式服务过渡到可重复产品的过程中，支持导入、工件清洗和客户信任建立。",
    "Customer success and partner manager": "客户成功与合作伙伴经理",
    "Month 9": "第 9 个月",
    "Needed once pilot accounts convert and CM or consultancy channels require structured enablement.": "当试点账户开始转化、且 CM 或咨询渠道需要结构化赋能时，此岗位必不可少。",
    "Validate the first-customer workflow with 10 design-partner teardowns and 5 live release pilots.": "通过 10 次设计合作伙伴拆解和 5 次真实发版试点，验证首批客户工作流。",
    "Launch the MVP release workspace covering BOM risk review, RFQ packet generation, and bring-up checklist creation.": "上线 MVP 发版工作台，覆盖 BOM 风险审查、RFQ 包生成和 bring-up 清单创建。",
    "Close 3-5 paid pilots and convert at least 2 into annual software contracts.": "达成 3-5 个付费试点，并至少将其中 2 个转化为年度软件合同。",
    "Support KiCad, Altium export, and spreadsheet BOM intake for the majority of pilot customers.": "为大多数试点客户支持 KiCad、Altium 导出和电子表格 BOM 接入。",
    "Establish at least 2 referral partners across CMs and embedded consultancies.": "在 CM 和嵌入式咨询公司中建立至少 2 个转介绍伙伴。",
    "Reach 15-20 paying accounts with repeatable onboarding and measured time-to-quote improvement.": "达到 15-20 个付费账户，实现可重复导入并量化报价时间改善。",
    "Ship revision intelligence, approval workflows, and confidence-scored alternate recommendations.": "上线修订智能、审批工作流以及带置信度评分的替代料推荐。",
    "Prove second-program or second-release expansion inside at least 30% of customers.": "证明至少 30% 的客户会扩展到第二个项目或第二次发版。",
    "Add supplier-performance and certification-readiness modules for the highest-frequency workflows.": "为最高频工作流增加供应商绩效和认证就绪度模块。",
    "Reach the year-3 case of roughly 65 paying accounts concentrated in startup and consultancy segments.": "达到第 3 年约 65 个付费账户的目标，客户集中在初创公司和咨询公司细分。",
    "Become the default neutral release-control layer for mixed-tool startup hardware teams in the beachhead.": "成为切入市场中、使用混合工具的初创硬件团队默认采用的中立发版控制层。",
    "Expand into adjacent device categories such as drones and industrial IoT without changing the core release workflow.": "在不改变核心发版工作流的前提下，扩展到无人机和工业 IoT 等相邻设备品类。",
    "Prepare the platform for deeper PLM, procurement, and compliance integrations once data scale is sufficient.": "当数据规模足够后，为平台做好更深层 PLM、采购和合规集成的准备。",
    "Customers may not trust the recommendations enough to use them in live pilot releases.": "客户可能不会足够信任这些建议，从而不愿在真实试产发版中使用。",
    "Launch with human-in-the-loop approvals, evidence-backed recommendations, and narrow scope around reviewable artifacts.": "以人机协同审批、基于证据的建议和围绕可审查工件的狭窄范围来启动产品。",
    "Early buyers may prefer service-heavy support over recurring software contracts.": "早期买方可能更偏好重服务支持，而不是持续性软件合同。",
    "Use paid pilots to discover the right software-to-service mix and only automate repeated high-value steps.": "通过付费试点探索恰当的软件与服务组合，并只自动化重复出现的高价值步骤。",
    "Incumbents can bundle handoff capabilities into ECAD or manufacturing suites.": "现有厂商可以将交接能力打包进 ECAD 或制造套件。",
    "Differentiate on manufacturer neutrality, mixed-tool support, and proprietary supplier outcome data.": "通过制造商中立性、混合工具支持和专有供应商结果数据实现差异化。",
    "Parser quality and external part-data quality may limit recommendation accuracy.": "解析器质量和外部器件数据质量可能限制建议准确率。",
    "Constrain supported inputs early, validate against human-reviewed releases, and choose data partners carefully.": "尽早收缩支持输入范围，对照人工审查的发版结果进行验证，并谨慎选择数据伙伴。",
    "Security and regulatory requirements may delay adoption in some hardware categories.": "安全与监管要求可能会推迟某些硬件品类的采用。",
    "Build auditable permissions and data controls early and focus first on lower-sensitivity customers.": "尽早建设可审计权限和数据控制，并优先聚焦敏感度较低的客户。",
    "Fund 18 months of runway to validate paid pilots, build the first release-control product, support mixed-tool interoperability, and prove repeatable startup and partner-driven distribution before scaling the team.": "提供 18 个月跑道，用于验证付费试点、构建首个发版控制产品、支持混合工具互操作性，并在扩大团队前证明面向初创公司及合作伙伴驱动的分发模式可以重复。",

    "Starting paying customers": "期初付费客户数",
    "Blended annual ARPU per paying account": "每个付费账户的混合年度 ARPU",
    "Gross margin target": "目标毛利率",
    "Monthly logo churn": "月度客户流失率",
    "Y1 customer additions": "Y1 新增客户",
    "Y2 ending customers": "Y2 期末客户数",
    "Y3 ending customers": "Y3 期末客户数",
    "Y2 quarterly net adds": "Y2 各季度净增",
    "Y3 quarterly net adds": "Y3 各季度净增",
    "Founding product and hardware operations lead salary": "创始产品与硬件运营负责人薪酬",
    "Engineering salary band": "工程岗位薪酬区间",
    "Solutions engineer salary": "解决方案工程师薪酬",
    "Customer success and partner manager salary": "客户成功与合作伙伴经理薪酬",
    "Sales hire salary": "销售岗位薪酬",
    "G&A and operations hire salary": "综合行政与运营岗位薪酬",
    "Y1 non-payroll opex": "Y1 非薪酬运营费用",
    "Y2 non-payroll opex": "Y2 非薪酬运营费用",
    "Y3 non-payroll opex": "Y3 非薪酬运营费用",
    "Fully diluted CAC": "完全摊薄 CAC",
    "Starting cash at model start": "模型起始现金",
    "Sales cycle": "销售周期",
    "[BP executiveSummary] Company is pre-launch and still validating 10 design-partner teardowns plus first live pilots.": "[BP executiveSummary] 公司尚未正式发布，仍在验证 10 个设计合作伙伴拆解与首批真实试点。",
    "[BP gtm pricing] $20k-$35k annual contracts plus usage-priced releases; modeled at a conservative blended $30k once pilots convert.": "[BP gtm pricing] 年度合同为 $20k-$35k，另加按次计费发版；模型在试点转化后按保守的混合 $30k 计。",
    "[Research openQuestions + startup-finance heuristic] Early workflow software for small hardware teams should assume modest churn until second-program expansion is proven.": "[Research openQuestions + startup-finance heuristic] 面向小型硬件团队的早期工作流软件，在第二项目扩展被证明前，应假设流失率较为温和。",
    "[BP milestones 0-12 months] Close 3-5 paid pilots and convert at least 2 into annual software contracts; modeled as 4 paying accounts by year end.": "[BP milestones 0-12 months] 达成 3-5 个付费试点，并至少将其中 2 个转化为年度软件合同；模型按年末 4 个付费账户计算。",
    "[BP milestones 12-24 months] Reach 15-20 paying accounts with repeatable onboarding.": "[BP milestones 12-24 months] 达到 15-20 个付费账户，并实现可重复导入。",
    "[BP market.som + BP milestones 24-36 months] Reach roughly 65 paying accounts in the year-3 case.": "[BP market.som + BP milestones 24-36 months] 在第 3 年情景中达到约 65 个付费账户。",
    "[BP milestones + startup-finance heuristic] Conservative ramp from founder-led sales and early channel referrals.": "[BP milestones + startup-finance heuristic] 基于创始人主导销售和早期渠道转介绍的保守增长曲线。",
    "[BP gtm channels + BP milestones 24-36 months] Acceleration assumes direct sales plus CM and consultancy referrals begin to work.": "[BP gtm channels + BP milestones 24-36 months] 加速增长假设直销以及 CM 和咨询伙伴转介绍开始奏效。",
    "[BP team] Founder below-market startup salary heuristic.": "[BP team] 采用创始人在初创阶段低于市场水平的薪酬假设。",
    "[BP team + startup-finance heuristic] One founding engineer, one applied data/workflow engineer, and one later senior engineer.": "[BP team + startup-finance heuristic] 包含 1 名创始工程师、1 名应用数据/工作流工程师，以及后续加入的 1 名资深工程师。",
    "[BP team] Customer-facing technical hire at month 6.": "[BP team] 在第 6 个月招聘面向客户的技术岗位。",
    "[BP team] Hire at month 9 to support conversions and referral channels.": "[BP team] 在第 9 个月招聘，以支持转化和转介绍渠道。",
    "[Startup-finance heuristic] Early account executive/BD role supporting founder-led motion after initial validation.": "[Startup-finance heuristic] 在初步验证后设置早期 AE/BD 岗位，以支持创始人主导的销售动作。",
    "[Startup-finance heuristic] Lean operations support added only after onboarding and partner workflows become repeatable.": "[Startup-finance heuristic] 只有在导入和合作伙伴工作流变得可重复后，才增加精简运营支持。",
    "[BP operations + startup-finance heuristic] Covers cloud, data providers, travel, legal, security, and content while product is still concierge-assisted.": "[BP operations + startup-finance heuristic] 在产品仍以礼宾式辅助为主时，覆盖云资源、数据提供商、差旅、法务、安全和内容等费用。",
    "[BP operations + startup-finance heuristic] Higher tooling, partner travel, and compliance overhead as onboarding scales.": "[BP operations + startup-finance heuristic] 随着导入扩张，工具、伙伴差旅和合规开销提升。",
    "[BP operations + startup-finance heuristic] Ongoing data-provider, security, and go-to-market support costs at moderate scale.": "[BP operations + startup-finance heuristic] 在中等规模下，持续发生的数据提供商、安全和市场推进支持成本。",
    "[BP gtm funnelTargets + startup-finance heuristic] Founder-led outbound and partner referrals should keep CAC below first-year gross profit.": "[BP gtm funnelTargets + startup-finance heuristic] 创始人主导外拓和伙伴转介绍应使 CAC 低于首年毛利润。",
    "[BP fundingAsk.targetFundingRangeUsd] Uses a $2.8M pre-seed inside the stated $2-4M range.": "[BP fundingAsk.targetFundingRangeUsd] 在声明的 $2-4M 区间内，采用 $2.8M 的 pre-seed 融资额。",
    "[Research buyingTriggers + startup-finance heuristic] Deadline-driven CM quote events compress evaluation relative to broad enterprise software.": "[Research buyingTriggers + startup-finance heuristic] 由截止时间驱动的 CM 询价事件，相比宽泛企业软件会缩短评估周期。",
    "Founding product and HW ops": "创始产品与硬件运营",
    "Engineering": "工程研发",
    "Solutions and onboarding": "解决方案与导入",
    "Customer success and partners": "客户成功与合作伙伴",
    "Sales": "销售",
    "G&A and operations": "综合行政与运营",
    "Reach 18 paying accounts, prove repeatable onboarding, and show CM/consultancy referral traction by Q4Y2 with six months of buffer.": "在 Q4Y2 前达到 18 个付费账户，证明导入可重复，并展示来自 CM/咨询伙伴转介绍的进展验证，同时保留 6 个月缓冲。",
    "Buffer (6 mo)": "缓冲资金（6 个月）",
    "Trust stays lower for machine-assisted alternates, so the business sells fewer annual contracts and more service-like pilots.": "市场对机器辅助替代料的信任仍偏低，因此公司卖出的年度合同更少，服务型试点更多。",
    "Blended ARPU falls to $27K.": "混合 ARPU 降至 $27K。",
    "Y3 ending customers fall to 50 instead of 65.": "Y3 期末客户数从 65 降至 50。",
    "Gross margin compresses to 70% because support stays human-heavy.": "由于支持仍高度依赖人工，毛利率压缩至 70%。",
    "Founder-led sales plus early partner referrals produce a steady ramp from 4 paying accounts in Y1 to 65 by Q4Y3.": "创始人主导销售加上早期伙伴转介绍，使付费账户从 Y1 的 4 个稳步增长到 Q4Y3 的 65 个。",
    "Blended ARPU stays at $30K.": "混合 ARPU 保持在 $30K。",
    "Gross margin stays at 75% with limited services creep.": "在服务扩张有限的情况下，毛利率维持在 75%。",
    "Hiring follows the staged plan and sales hiring waits for Q2Y2 proof.": "招聘按分阶段计划推进，销售岗位招聘推迟到 Q2Y2 验证之后。",
    "Consultancy and CM channels convert faster than expected, lifting both customer count and usage revenue without needing a much larger team.": "咨询公司和 CM 渠道转化速度快于预期，在无需大幅扩大团队的前提下，同时提升客户数和使用收入。",
    "Blended ARPU rises to $32K.": "混合 ARPU 升至 $32K。",
    "Y3 ending customers reach 80.": "Y3 期末客户数达到 80。",
    "Gross margin expands to 78% as onboarding becomes more productized.": "随着导入更加产品化，毛利率提升至 78%。",
    "ARPU": "ARPU",
    "CAC": "CAC",
    "churn": "流失率",
    "sales cycle": "销售周期",
    "gross margin": "毛利率",
    "hiring pace": "招聘节奏",
    "unit economics flow": "单位经济模型流转",
    """flowchart LR
Leads --> QualifiedPilots
QualifiedPilots --> PayingAccounts
PayingAccounts --> SubscriptionRevenue
PayingAccounts --> ReleaseUsageRevenue
SubscriptionRevenue --> GrossProfit
ReleaseUsageRevenue --> GrossProfit
GrossProfit --> Opex
Opex --> Cash
""": """flowchart LR
Leads[线索] --> QualifiedPilots[合格试点]
QualifiedPilots --> PayingAccounts[付费账户]
PayingAccounts --> SubscriptionRevenue[订阅收入]
PayingAccounts --> ReleaseUsageRevenue[发版使用收入]
SubscriptionRevenue --> GrossProfit[毛利润]
ReleaseUsageRevenue --> GrossProfit
GrossProfit --> Opex[运营费用]
Opex --> Cash[现金]
""",
    "Revenue engine": "收入引擎",
    "Base-case revenue comes from reaching 65 paying accounts by Q4Y3 at a $30K blended ARPU driven by founder-led sales and partner referrals.": "基准情景收入来自在创始人主导销售和伙伴转介绍带动下，于 Q4Y3 达到 65 个付费账户、混合 ARPU 为 $30K。",
    "Must go right": "必须成立的条件",
    "Paid pilots must convert into annual contracts quickly enough to justify the first sales hire only after onboarding and product trust are proven.": "付费试点必须足够快地转化为年度合同，才能证明应在导入和产品信任被验证后再招聘首名销售。",
    "Model breaks if": "模型失效条件",
    "The downside case appears if customers keep demanding service-heavy review of alternates, which cuts ARPU and margin and drives cash toward roughly $410K.": "如果客户持续要求对替代料进行重服务式审核，就会出现下行情景，导致 ARPU 与毛利率下降，并使现金降至约 $410K。",
    "Next-round proof": "下一轮融资所需证明",
    "The seed story is strongest once the company reaches 18 paying accounts with repeatable onboarding and at least some CM or consultancy-sourced pipeline by Q4Y2.": "一旦公司在 Q4Y2 前达到 18 个付费账户、实现可重复导入，并获得一定来自 CM 或咨询伙伴的销售管道，种子轮故事就最具说服力。",
    "Revenue per FTE is still below software benchmarks, so the model needs higher ACV, more automation, or tighter hiring discipline before a large seed expansion.": "每名 FTE 对应收入仍低于软件行业基准，因此在进行更大规模 seed 扩张前，模型需要更高 ACV、更多自动化或更严格的招聘纪律。",
    "Gross margin assumes human review remains scoped to exceptions; if onboarding and alternate approval become service-heavy, margin can fall below the 75% target.": "毛利率假设人工审查仅限于例外情况；若导入和替代料审批变得重服务化，毛利率可能跌破 75% 目标。",
    "The customer ramp relies on CM and consultancy referrals that research supports directionally but the company has not yet validated in-market.": "客户增长依赖 CM 和咨询伙伴转介绍，研究在方向上支持这一点，但公司尚未在市场中完成验证。",

    "canonical URL + normalized title + event/company/date + fetched-body similarity + source-family check": "规范 URL + 标准化标题 + 事件/公司/日期 + 抓取正文相似度 + 来源家族校验",
    "JITX homepage vs product landing": "JITX 首页与产品落地页",
    "near-identical body": "正文几乎相同",
    "Fictiv home vs hardware guide": "Fictiv 首页与硬件指南",
    "Altium BOM management landing duplication": "Altium BOM 管理落地页重复",
    "same source family": "同一来源家族",
    "Altium pricing duplicate": "Altium 定价页重复",
    "Nexar product shell duplicates": "Nexar 产品壳页重复",
    "MacroFab inaccessible capability duplicates": "MacroFab 无法访问的能力页重复",
    "same event": "同一事件",
    "AI is lowering the cost of generating first-pass hardware concepts, but the evidence base shows the next acute bottleneck is still BOM risk, sourcing, assembly, and release control rather than schematic capture itself [1][8][18][19][21][26].": "AI 正在降低首版硬件概念生成的成本，但证据表明，下一个尖锐瓶颈仍是 BOM 风险、采购、装配和发版控制，而不是原理图绘制本身 [1][8][18][19][21][26]。",
    "The beachhead is attractive because it is narrow and deadline-driven: small robotics and industrial-device teams hit a painful \"first CM quote / first pilot build\" moment where manual workflows break down fast [3][4][9][10][15][16].": "这个切入市场之所以有吸引力，是因为它狭窄且受截止时间驱动：小型机器人和工业设备团队会在“首次 CM 报价 / 首次试产”这一痛苦节点上迅速暴露手工工作流失效的问题 [3][4][9][10][15][16]。",
    "Incumbents cover fragments of the workflow, yet none appears optimized for a manufacturer-agnostic, startup-specific handoff layer that turns partial design artifacts into a traceable pilot-build package [18][19][21][22][24][26].": "现有厂商覆盖了该工作流的若干碎片，但没有一家看起来真正针对“与制造商无关、面向初创公司、将不完整设计工件转化为可追溯试产包”的交接层进行优化 [18][19][21][22][24][26]。",
    "Willingness to pay exists only if the product is sold against avoided respins, engineer-hours, and consultant/CM coordination near release, not as another generic AI design copilot [6][8][15][17][23].": "只有当产品围绕避免重转板、节省工程师工时以及减少临近发版时的顾问/CM 协调成本来销售时，付费意愿才会存在，而不是把它包装成另一个通用 AI 设计副驾 [6][8][15][17][23]。",
    "Open source and manual stacks remain the default for cash-constrained teams, so the startup must win on speed-to-quote and risk reduction, not on authoring features alone [27][28][30][40].": "对于现金紧张的团队来说，开源和手工堆栈仍是默认选择，因此创业公司必须在报价速度和风险降低上胜出，而不能只靠设计创作功能 [27][28][30][40]。",
    "Category timing looks favorable: robotics demand is still expanding, AI and digital manufacturing are becoming core infrastructure, and supply-chain volatility keeps increasing the value of structured BOM intelligence [2][3][4][5][6][33].": "品类时机看起来有利：机器人需求仍在扩张，AI 与数字化制造正在成为核心基础设施，而供应链波动持续提升结构化 BOM 情报的价值 [2][3][4][5][6][33]。",
    "Workflow software for prototype-to-production electronics handoff: converting early PCB/BOM artifacts into manufacturable pilot-build release packages with BOM health, approved alternates, CM-ready RFQ files, assembly notes, and bring-up/test traceability for seed-to-Series A robotics and industrial-device teams in North America and Europe. It excludes generic PCB authoring, full PLM/ERP suites, and commodity fab marketplaces [18][19][21][22][25][27].": "用于电子产品原型到量产交接的工作流软件：面向北美和欧洲的种子轮至 Series A 机器人与工业设备团队，将早期 PCB/BOM 工件转化为可制造的试产发版包，包含 BOM 健康度、已批准替代料、可交付给 CM 的 RFQ 文件、装配说明以及 bring-up/测试可追溯性。它不包括通用 PCB 创作、完整 PLM/ERP 套件和标准化制造市场 [18][19][21][22][25][27]。",
    "ICP is a 10-80 person robotics or industrial-device company with one or two electrical engineers that is moving off dev boards into its first custom PCB for 10-500 pilot units. The day-to-day user is the founding EE or embedded lead; the economic buyer is the CTO or Head of Hardware. Pain emerges when procurement, CM quoting, and bring-up planning start before documentation is production-grade, creating version errors, alternate-part churn, and manual re-entry across spreadsheets, distributor portals, and email threads [15][18][19][25].": "ICP 是一家 10-80 人规模的机器人或工业设备公司，只有一到两名电气工程师，正从开发板转向首块面向 10-500 台试产规模的定制 PCB。日常使用者是创始 EE 或嵌入式负责人；经济买方是 CTO 或硬件负责人。当采购、CM 报价和 bring-up 规划在文档尚未达到量产级别之前启动时，痛点就会出现，表现为版本错误、替代料反复，以及在表格、分销商门户和邮件往来中的反复手工录入 [15][18][19][25]。",
    "Pilot deployment commitment forces the team to request its first serious CM quotes and assemble a release package fast.": "试点部署承诺迫使团队必须快速发起首次正式 CM 询价并组装发版包。",
    "Shortages, lifecycle flags, or part substitutions expose that prototype BOMs are not yet procurement-ready.": "缺货、生命周期预警或器件替换会暴露出原型 BOM 尚未达到可采购状态。",
    "Distributed collaborators or external partners create version-control and release-control failure modes.": "分布式协作者或外部合作方会带来版本控制和发版控制失效模式。",
    "Budget exists when the software displaces manual NPI coordination: Altium prices adjacent collaboration annually and sells extra design-author seats for $995/year each, while Fictiv documents that engineers are still spending material time on procurement and NPI coordination. The value case is avoided respins, faster quotes, and less EE time lost to sourcing/admin work [6][15][17][23].": "当软件能够替代手工 NPI 协调时，预算就会出现：Altium 对相邻协作能力按年收费，额外设计作者席位价格为每年 $995，而 Fictiv 也记录了工程师仍在采购和 NPI 协调上花费大量时间。价值主张在于避免重转板、加快报价，以及减少 EE 在采购/行政工作上的时间损失 [6][15][17][23]。",
    "Altium owns the broad ECAD collaboration stack; JITX and Atech attack upstream AI-driven design generation; Fictiv and CM-centric platforms monetize execution-heavy NPI/manufacturing services; KiCad plus spreadsheets remains the price-sensitive default. The proposed startup is most differentiated if it becomes the neutral operating layer between design output and supplier-ready pilot release, rather than trying to out-CAD the CAD vendors or out-manufacture the manufacturers [1][18][19][21][24][26][27][28].": "Altium 掌控了广义 ECAD 协作栈；JITX 和 Atech 攻击的是上游 AI 驱动设计生成；Fictiv 和以 CM 为中心的平台则将执行密集型 NPI/制造服务货币化；KiCad 加电子表格仍是价格敏感客户的默认方案。如果这家创业公司能成为设计输出与供应商就绪试产发版之间的中立运营层，而不是试图在 CAD 上胜过 CAD 厂商或在制造上胜过制造商，它就最具差异化 [1][18][19][21][24][26][27][28]。",
    "Altium already connects design, BOM, and manufacturing data, but its product and pricing model remain broad, design-centric, and not purpose-built for startup first-board handoff across mixed tools and mixed CMs.": "Altium 已将设计、BOM 和制造数据连接起来，但其产品与定价模型仍然宽泛且以设计为中心，并非专为初创公司在混合工具和混合 CM 环境中的首板交接而设计。",
    "Fictiv-like platforms win once a team is inside their sourcing/manufacturing workflow, but they are economically tied to their network and service layers; a neutral release-control layer can sit earlier and across suppliers.": "类似 Fictiv 的平台一旦将团队纳入其采购/制造工作流就会占优，但它们在经济上绑定于自身网络和服务层；一个中立的发版控制层可以更早介入，并跨越多个供应商。",
    "JITX and Atech reduce concept and layout effort, which likely increases downstream handoff demand rather than eliminating it; they solve earlier abstraction layers than CM-ready release packaging.": "JITX 和 Atech 降低了概念设计和布局工作量，这更可能增加下游交接需求，而不是消除它；它们解决的是比 CM 就绪发版打包更早的抽象层问题。",
    "KiCad is a credible free default and is getting more interoperable, but it does not provide managed BOM risk, procurement collaboration, or release-traceability out of the box.": "KiCad 是一个可信的免费默认方案，而且互操作性正在增强，但它并不能开箱即用地提供受管理的 BOM 风险、采购协作或发版可追溯性。",
    "Human experts can bridge the gap for first programs, but the knowledge stays trapped in people and email; software wins if it captures accepted alternates, DFM issues, and bring-up outcomes as reusable data.": "人工专家可以弥补首个项目中的缺口，但知识会被困在个人和邮件中；如果软件能把已接受替代料、DFM 问题和 bring-up 结果沉淀为可复用数据，它就能胜出。",
    "For connected hardware, manufacturing handoff increasingly includes certification and security obligations, not just fabrication files. FCC/EMC failure risk, export-control boundaries, cloud data-security expectations, and emerging security-by-design norms all increase the value of traceable release packets and audit trails [11][12][13][14][38].": "对于联网硬件而言，制造交接越来越不仅是提供生产文件，还包括认证和安全义务。FCC/EMC 失败风险、出口管制边界、云数据安全预期以及新兴的安全内建规范，都在提升可追溯发版包和审计追踪的价值 [11][12][13][14][38]。",
    "The enabling stack is converging: upstream AI-driven design generation is improving, KiCad is reducing proprietary lock-in with new importers, and incumbents are embedding live part intelligence and PLM sync into ECAD workflows. That raises the bar for any startup to focus narrowly on the messy last mile between prototype artifacts and supplier-ready execution [18][20][21][22][24][26][27][28].": "使能技术栈正在汇合：上游 AI 驱动设计生成不断改进，KiCad 通过新的导入器降低专有锁定，现有厂商也在将实时器件情报和 PLM 同步嵌入 ECAD 工作流。这提高了对任何创业公司的要求：必须聚焦在原型工件到供应商就绪执行之间那段混乱的最后一公里 [18][20][21][22][24][26][27][28]。",
    "Founder-led outbound into robotics and industrial-device startups at the dev-board-to-custom-board transition is the cleanest initial motion.": "在开发板向定制板过渡阶段，由创始人主导面向机器人和工业设备初创公司的外拓，是最干净的初始动作。",
    "Design consultancies and CMs are strong referral channels because they see release-package failures early and repeatedly.": "设计咨询公司和 CM 是很强的转介绍渠道，因为它们会更早且反复地看到发版包失败问题。",
    "Technical content around BOM risk, DFM, NPI, and certification pain can create inbound demand without competing head-on in CAD keywords.": "围绕 BOM 风险、DFM、NPI 和认证痛点的技术内容，可以在不与 CAD 关键词正面竞争的情况下创造 inbound 需求。",
    "Part-data and risk partners such as Octopart, SiliconExpert, and Z2Data are core to any credible alternates/reliability workflow.": "Octopart、SiliconExpert 和 Z2Data 等器件数据与风险合作方，是任何可信替代料/可靠性工作流的核心。",
    "Cloud PLM and release-system integrations help the product avoid becoming just another export utility.": "云 PLM 和发版系统集成有助于产品避免沦为又一个导出工具。",
    "CMs and embedded consultancies can provide labeled feedback on accepted alternates, DFM defects, and quote readiness.": "CM 和嵌入式咨询公司可以就已接受替代料、DFM 缺陷和报价就绪度提供带标注反馈。",
    "A proprietary graph of accepted alternates, lifecycle exceptions, and quote outcomes could compound faster than generic CAD features.": "一个关于已接受替代料、生命周期例外和报价结果的专有图谱，其积累速度可能快于通用 CAD 功能。",
    "Revision-linked bring-up failures and first-article findings are sticky workflow data that incumbents do not consistently capture across suppliers.": "与修订关联的 bring-up 失败和首件发现，是一种粘性很强的工作流数据，而现有厂商并不能在跨供应商场景中稳定捕获。",
    "North America and Western Europe are the logical first focus because robot density is high and automation investment remains strong.": "北美和西欧是合理的第一聚焦区域，因为当地机器人密度高，自动化投资也持续强劲。",
    "Any product that ignores Asia-based sourcing dynamics will underperform because component availability and price intelligence are globally determined.": "任何忽视亚洲供应链动态的产品都会表现不佳，因为元器件可得性和价格情报是全球决定的。",
    "Open-source-heavy customer mix": "开源占比高的客户结构",
    "If most early adopters are KiCad-plus-spreadsheet teams shipping only one board release per year, ACV compresses and services may dominate software revenue.": "如果大多数早期采用者都是使用 KiCad 加电子表格、且每年只发一次板的团队，那么 ACV 会被压缩，服务收入也可能超过软件收入。",
    "Broader channel into consultancies and OEM design partners": "向咨询公司和 OEM 设计伙伴扩展更广渠道",
    "If the product proves useful for repeat client programs at consultancies, SAM expands materially beyond startup budgets.": "如果产品被证明适用于咨询公司中重复性的客户项目，SAM 将显著超出初创公司的预算边界。",
    "Incumbent feature catch-up": "现有厂商功能追赶",
    "If Altium or a CM platform automates alternates and manufacturing packets deeply enough, the startup must differentiate on supplier-agnostic release intelligence and feedback data.": "如果 Altium 或某个 CM 平台足够深入地自动化了替代料和制造资料包，创业公司就必须在与供应商无关的发版智能和反馈数据上建立差异化。",
    "Which artifact is the true wedge: BOM alternates, RFQ packet generation, or bring-up/test planning?": "真正的切口工件是什么：BOM 替代料、RFQ 包生成，还是 bring-up/测试规划？",
    "Collect the last three release packages from 10 target teams and time each manual step end-to-end.": "从 10 个目标团队收集最近三份发版包，并对每个手工步骤做端到端计时。",
    "Will CTOs trust machine-generated alternates and DFM flags enough to send them to a CM?": "CTO 是否会足够信任机器生成的替代料和 DFM 标记，从而将其发送给 CM？",
    "Run concierge pilots with 5 CMs or design consultancies and score false positives/false negatives on live boards.": "与 5 家 CM 或设计咨询公司开展礼宾式试点，并在真实板卡上评估误报/漏报。",
    "Is budget software-first or service-first at the first pilot-build trigger?": "在首次试产触发点，预算更偏向软件优先还是服务优先？",
    "Test paid design-review + release-package concierge offers before offering pure software contracts.": "在提供纯软件合同前，先测试付费设计审查 + 发版包礼宾式服务报价。",
    "Which channel converts fastest: direct founder sales, CMs, or consultancies?": "哪个渠道转化最快：创始人直销、CM，还是咨询公司？",
    "Track intro-to-pilot conversion and time-to-close across each channel for the first 20 opportunities.": "针对前 20 个机会，跟踪各渠道从引荐到试点的转化率和成交时间。",
    "Prototype-to-production handoff market map": "原型到量产交接市场图谱",
    "quadrantChart\n  title Market map\n  x-axis Low manufacturing handoff depth --> High manufacturing handoff depth\n  y-axis Low startup specificity --> High startup specificity\n  Altium 365: [0.56, 0.34]\n  JITX: [0.42, 0.31]\n  Fictiv: [0.68, 0.27]\n  KiCad manual stack: [0.18, 0.61]\n  Proposed startup: [0.82, 0.88]\n": "quadrantChart\n  title 市场图谱\n  x-axis 制造交接深度低 --> 制造交接深度高\n  y-axis 面向初创公司特异性低 --> 面向初创公司特异性高\n  Altium 365: [0.56, 0.34]\n  JITX: [0.42, 0.31]\n  Fictiv: [0.68, 0.27]\n  KiCad 手工工具栈: [0.18, 0.61]\n  拟议创业公司: [0.82, 0.88]\n",
    "Cloud platforms": "云平台",
    "Digital manufacturing networks": "数字制造网络",
    "AI design generators": "AI 设计生成器",
    "In-house and consultancies": "内部团队与咨询公司",
    "CTO / Head of Hardware": "CTO / 硬件负责人",
    "0-12 months": "0-12 个月",
    "12-24 months": "12-24 个月",
    "24-36 months": "24-36 个月",
    "High": "高",
    "Medium": "中",
    "Low": "低",
    "$27K blended annual ARPU": "$27K 混合年度 ARPU",
    "$30K blended annual ARPU": "$30K 混合年度 ARPU",
    "$33K blended annual ARPU": "$33K 混合年度 ARPU",
    "$18K CAC from weaker partner conversion": "由于合作伙伴转化较弱，CAC 为 $18K",
    "$13.5K CAC": "$13.5K CAC",
    "$10K CAC from strong referrals": "由于转介绍强劲，CAC 为 $10K",
    "2.0% monthly churn": "2.0% 月度流失率",
    "1.4% monthly churn": "1.4% 月度流失率",
    "1.0% monthly churn": "1.0% 月度流失率",
    "6-month sales cycle": "6 个月销售周期",
    "90-day sales cycle": "90 天销售周期",
    "60-day sales cycle": "60 天销售周期",
    "70% GM because onboarding remains service-heavy": "由于导入仍偏重服务，GM 为 70%",
    "75% GM": "75% GM",
    "78% GM": "78% GM",
    "Two GTM and ops hires are pulled forward by two quarters": "两个 GTM 与运营岗位提前两个季度招聘",
    "Current staged hiring plan": "当前分阶段招聘计划",
    "One non-engineering hire delayed by one quarter": "一个非工程岗位延后一个季度招聘",
    "Y3 burn multiple is approximately 0.3x using $450K net burn over roughly $1.41M of net new ARR.": "以约 $1.41M 的净新增 ARR 和 $450K 的净消耗计算，Y3 burn multiple 约为 0.3x。",
    "$126K Y3 on 9 exit FTE versus a rough $200-400K SaaS benchmark.": "Y3 在 9 名期末 FTE 下的人均收入为 $126K，对比 SaaS 粗略基准 $200-400K。",
    "est. narrowed from broader electronics-tooling base using [3] [4] [15]": "基于 [3] [4] [15]，从更广泛的电子工具市场基础中收窄估算",
    "[23] + service-heavy alternatives in [8] [10] [15]": "[23] + [8] [10] [15] 中偏服务型替代方案",
    "$22.5k est.": "估算 $22.5k",
    "65 est.": "估算 65",
    "Core data inputs sit with part-data providers, distributors, and CMs, but there are multiple vendors and the startup can begin with semi-manual workflows before deep integration.": "核心数据输入掌握在器件数据提供商、分销商和 CM 手中，但供应方不止一家，创业公司也可以在深度集成前先从半手工工作流起步。",
    "Early customers are small, technical, and price-sensitive, with credible manual and open-source fallbacks, so switching costs are initially low.": "早期客户规模小、技术导向且价格敏感，并且存在可信的手工和开源替代方案，因此初期切换成本较低。",
    "Software barriers are moderate, but trusted manufacturing knowledge, outcome data, and integration depth make the category harder than a shallow AI wrapper.": "软件门槛中等，但受信任的制造知识、结果数据和集成深度，使这一品类比浅层 AI 套壳更难。",
    "Consultants, CM engineering teams, and existing CAD-plus-spreadsheet workflows can all solve the job badly but sufficiently for early teams.": "顾问、CM 工程团队以及现有 CAD 加电子表格工作流，都能以不够理想但勉强足够的方式解决早期团队的问题。",
    "Adjacent incumbents already attack BOM, sourcing, collaboration, or manufacturing execution, so any startup must hold a narrow wedge to avoid feature overlap.": "相邻领域的现有厂商已经覆盖 BOM、采购、协作或制造执行，因此任何创业公司都必须占据一个狭窄切口，才能避免功能重叠。",
    "Automation demand and robot installations continue to grow, supporting a larger installed base of teams building custom hardware.": "自动化需求和机器人装机量持续增长，为开发定制硬件的团队提供了更大的存量基础。",
    "AI is moving into core manufacturing and robotics workflows, making AI-native handoff tools more believable to buyers.": "AI 正在进入制造和机器人核心工作流，使 AI 原生交接工具对买方来说更具可信度。",
    "Certification, export-control, and security expectations create liability if release recommendations are wrong.": "如果发版建议出错，认证、出口管制和安全预期会带来责任风险。",
    "Small distributed hardware teams increasingly expect cloud collaboration and faster iteration cycles.": "小型分布式硬件团队越来越期待云端协作和更快的迭代周期。",
    "Tariffs and trade-policy volatility can force redesigns and create noisy demand that is partly macro rather than product-led.": "关税和贸易政策波动会迫使重新设计，并带来部分由宏观因素而非产品本身驱动的噪声需求。",
    "Trust in alternate-part recommendations": "对替代料建议的信任",
    "Start human-in-the-loop with confidence scores and explicit approval logs.": "从人机协同开始，提供置信度评分和明确的审批日志。",
    "Messy multi-tool inputs across Altium, KiCad, Gerbers, and spreadsheets": "来自 Altium、KiCad、Gerber 和电子表格的混乱多工具输入",
    "Founding EE": "创始 EE",
    "Prioritize ingestion of exported BOMs, Gerbers, and PDFs before native CAD integrations.": "在原生 CAD 集成之前，优先支持导出 BOM、Gerber 和 PDF 的接入。",
    "Budget sensitivity before repeat production programs": "在重复量产项目出现前，对预算高度敏感",
    "Startup CTO": "初创公司 CTO",
    "Sell against first pilot-release ROI or package as a service-assisted workflow initially.": "围绕首次试产发版的 ROI 销售，或在初期将其包装为服务辅助型工作流。",
    "Compliance and security concerns for design data": "围绕设计数据的合规与安全担忧",
    "IT / operations stakeholder": "IT / 运营相关方",
    "Offer auditable permissions, region controls, and traceable release history from day one.": "从第一天起就提供可审计权限、区域控制和可追溯发版历史。",
    "Channel conflict with design consultancies and CMs": "与设计咨询公司和 CM 的渠道冲突",
    "Partner channel": "合作伙伴渠道",
    "Position as neutral release-control software that makes partners faster rather than replacing them.": "将产品定位为让伙伴更高效、而非取代伙伴的中立发版控制软件。",
    "Bottom-up estimate: ~8,000 global electronics teams with recurring board-release handoff pain × ~$22.5k blended annual spend for platform + release usage; constrained by Altium's 10,000+ organization footprint and broad open-source KiCad activity, then narrowed to teams where manufacturing handoff is acute.": "自下而上估算：约 8,000 个全球电子团队存在持续性的板卡发版交接痛点，按平台 + 按次发版使用的混合年度支出约 $22.5k 计算；再结合 Altium 覆盖 10,000+ 组织的足迹以及广泛的开源 KiCad 活动，收窄到制造交接痛点最尖锐的团队。",
    "Bottom-up estimate: ~1,500 North America/Europe seed-to-Series A robotics, industrial-device startups, and embedded consultancies × ~$22.5k blended annual spend.": "自下而上估算：约 1,500 家北美/欧洲的种子轮至 Series A 机器人、工业设备初创公司和嵌入式咨询公司，乘以约 $22.5k 的混合年度支出。",
    "Reachable year-3 case: ~65 paying accounts at ~$25k ACV through founder-led sales plus CM/consultancy referrals, focused on first pilot-board programs.": "可触达的第 3 年情景：通过创始人主导销售加 CM/咨询伙伴转介绍，围绕首个试产板项目拿下约 65 个付费账户，ACV 约为 $25k。",
    "Total addressable units": "可触达总单位数",
    "8,000 est. global electronics teams with recurring board-release handoff needs": "估算 8,000 个存在持续板卡发版交接需求的全球电子团队",
    "Beachhead units": "切入市场单位数",
    "1,500 est. NA/EU robotics, industrial-device, and consultancy teams": "估算 1,500 个北美/欧洲机器人、工业设备与咨询团队",
    "Blended annual spend per account": "每账户混合年度支出",
    "Reachable Y3 accounts": "Y3 可触达账户数",
    "Industrial robot market value and installations remain large enough to keep new hardware programs flowing.": "工业机器人市场规模和装机量仍足够大，能够持续推动新的硬件项目出现。",
    "AI is now treated as required infrastructure inside manufacturing and supply-chain operations.": "AI 现在正被视为制造和供应链运营中的必备基础设施。",
    "Incumbents are digitizing electronics procurement, validating the importance of BOM and risk workflows.": "现有厂商正在推动电子采购数字化，这验证了 BOM 和风险工作流的重要性。",
    "Open-source interoperability improvements make mixed-tool environments more common and create demand for neutral workflow layers.": "开源互操作性的提升，使混合工具环境更加常见，并创造了对中立工作流层的需求。",
    "Manual stacks remain workable for very small teams and can delay software purchase timing.": "对非常小的团队而言，手工工具栈仍然可用，并可能推迟软件购买时点。",
    "Adjacent incumbents can bundle overlapping functionality into broader suites.": "相邻领域的现有厂商可以把重叠功能打包进更广泛的套件中。",
    "Bad alternate or compliance guidance could create outsized trust and liability damage.": "错误的替代料或合规指导可能造成超额的信任与责任损害。",
    "Integrated ECAD collaboration, BOM intelligence, and manufacturing handoff inside the dominant design stack.": "在主导设计栈内部整合 ECAD 协作、BOM 智能和制造交接。",
    "Annual seat-based pricing; extra Altium Designer ECAD Design Authors are $995/year each.": "按年按席位收费；额外 Altium Designer ECAD Design Author 席位为每年 $995。",
    "Deep integration across design, BOM, and PLM with broad installed base.": "在设计、BOM 和 PLM 之间具备深度集成，并拥有广泛装机基础。",
    "Broad, design-centric suite; not purpose-built for startup first-board release across mixed tools and mixed CMs.": "宽泛且以设计为中心的套件；并非专为初创公司在混合工具和混合 CM 环境中的首板发版而设计。",
    "Requirements-driven PCB generation and optimization with manufacturing rules captured in code.": "以需求驱动 PCB 生成和优化，并将制造规则编码化。",
    "Standard licensing; public price not listed.": "标准授权模式；未公开价格。",
    "Strong upstream automation for board design and validation.": "在板卡设计与验证的上游自动化能力强。",
    "Focused upstream on design generation, not CM-ready RFQ packets, approved alternates, or bring-up/release traceability.": "聚焦上游设计生成，而非可交付给 CM 的 RFQ 包、已批准替代料或 bring-up/发版可追溯性。",
    "Service-heavy digital manufacturing, NPI, and supply-chain orchestration from prototype to production.": "从原型到量产，提供重服务型数字制造、NPI 和供应链编排。",
    "Quote-based manufacturing and engineering services.": "按报价提供制造和工程服务。",
    "Strong DFM/DFX expertise, quality processes, and execution support.": "具备强 DFM/DFX 专长、质量流程和执行支持能力。",
    "Tied to its manufacturing network and broader mechanical scope rather than a neutral electronics handoff system of record.": "其能力绑定于自身制造网络和更广的机械范围，而不是中立的电子交接系统记录层。",
    "Prompt-native hardware configuration and code generation for very early hardware creation.": "面向超早期硬件创建的原生提示式硬件配置与代码生成。",
    "Pre-order/waitlist; public pricing not listed.": "预购/候补名单模式；未公开价格。",
    "Category-shaping UX for AI-generated hardware concepts.": "为 AI 生成硬件概念塑造品类的用户体验。",
    "More likely to generate downstream handoff demand than to solve CM-ready release complexity.": "更可能创造下游交接需求，而不是解决可交付给 CM 的发版复杂性。",
    "Zero-license-cost PCB design with flexible exports and broad interoperability.": "零许可成本的 PCB 设计方案，具备灵活导出和广泛互操作性。",
    "Free software plus manual labor.": "免费软件 + 人工劳动。",
    "Credible default for lean teams and increasingly interoperable with proprietary formats.": "是精简团队可信的默认方案，并与专有格式的互操作性不断增强。",
    "No managed BOM health, approval workflow, or release-traceability layer.": "没有受管理的 BOM 健康度、审批工作流或发版可追溯层。",
    "Certification and EMC failures can stop launches and add delay/cost, so release outputs need to support test readiness rather than just fab readiness.": "认证和 EMC 失败会阻断发布并增加延迟/成本，因此发版输出必须支持测试就绪，而不只是生产就绪。",
    "Export-control constraints and data-handling rules can limit where builds and design data can move.": "出口管制约束和数据处理规则会限制构建与设计数据的流转范围。",
    "Cloud collaboration in hardware increasingly requires auditable permissions, uptime commitments, and security response processes.": "硬件领域的云端协作越来越需要可审计权限、可用性承诺和安全响应流程。",
    "Part-risk intelligence depends on third-party data quality from providers such as Octopart, SiliconExpert, and Z2Data.": "器件风险情报依赖于 Octopart、SiliconExpert 和 Z2Data 等第三方数据提供商的数据质量。",
    "Mixed-tool interoperability remains necessary because early teams span Altium, KiCad, Gerbers, and manual spreadsheets.": "混合工具互操作性仍然是必要条件，因为早期团队往往同时使用 Altium、KiCad、Gerber 和手工电子表格。",
    "Atech's pre-seed financing is a direct signal that investors think AI-native hardware workflows are forming now.": "Atech 的 pre-seed 融资直接表明，投资人认为 AI 原生硬件工作流正在形成。",
    "IFR reports the industrial robot installation market hit a record value of $16.7B, supporting continued hardware program creation.": "IFR 报告称工业机器人装机市场达到创纪录的 $16.7B，支撑硬件项目持续产生。",
    "Fictiv reports near-universal AI and digital-manufacturing adoption among manufacturing leaders.": "Fictiv 报告称，制造业领导者几乎普遍采用 AI 和数字化制造。",
    "Altium's January 2025 acquisition of Part Analytics shows procurement digitization is strategically valuable to incumbents.": "Altium 于 2025 年 1 月收购 Part Analytics，表明采购数字化对现有厂商具有战略价值。",
    "Luxonis publicly credits Altium 365 with reducing version-control errors and respins in AI vision hardware development.": "Luxonis 公开表示，Altium 365 帮助其在 AI 视觉硬件开发中减少了版本控制错误和重转板。",
    "KiCad continues to add importers from major proprietary tools, expanding the open-source share of the electronics workflow.": "KiCad 持续增加对主流专有工具的导入器，扩大了开源方案在电子工作流中的份额。",
    "Fictiv launched landed-cost and tariff tooling, underscoring growing operational complexity around hardware sourcing.": "Fictiv 推出到岸成本和关税工具，凸显硬件采购周边运营复杂度正在上升。",
    "Can the product generate alternate-part and DFM recommendations with low enough error rates that CTOs will trust them before quote submission?": "产品能否以足够低的错误率生成替代料和 DFM 建议，使 CTO 在报价提交前就愿意信任它？",
    "Will early buyers prefer a service-assisted release workflow over pure software until they have multiple active board programs?": "在拥有多个活跃板卡项目之前，早期买方是否会更偏好服务辅助型发版工作流，而非纯软件？",
    "Which output is most valuable at purchase time: RFQ packet generation, BOM risk reduction, or bring-up/test traceability?": "在购买时最有价值的输出是什么：RFQ 包生成、BOM 风险降低，还是 bring-up/测试可追溯性？",
    "Can CM and consultancy partners become repeatable channels without viewing the startup as a threat to their engineering revenue?": "CM 和咨询伙伴能否在不把创业公司视为工程收入威胁的前提下，成为可重复渠道？",
    "Category-formation signal for prompt-native hardware creation that shifts pain downstream into manufacturing handoff.": "提示原生硬件创建这一品类正在形成的信号，并将痛点推向下游制造交接环节。",
    "Incumbent digital PCB manufacturing benchmark for quoting, sourcing, and revision tracking.": "用于报价、采购和修订跟踪的现有数字 PCB 制造基准。",
    "Adjacent AI PCB-design automation benchmark focused upstream of production handoff.": "聚焦量产交接上游的相邻 AI PCB 设计自动化基准。",
    "Incumbent evidence on BOM, sourcing, or manufacturing-handoff capabilities inside the dominant ECAD stack.": "主导 ECAD 栈内部关于 BOM、采购或制造交接能力的现有厂商证据。",
    "Packaging benchmark for adjacent electronics development software.": "相邻电子开发软件的打包与定价基准。",
    "Security/compliance baseline for cloud electronics workflows in regulated environments.": "受监管环境中云端电子工作流的安全/合规基线。",
    "Customer proof that hardware teams buy collaboration and release-control tooling to reduce errors and respins.": "客户层面的证明：硬件团队会购买协作与发版控制工具，以减少错误和重转板。",
    "Evidence of NPI, DFM, sourcing, quality, or compliance pain in prototype-to-production transitions.": "证明在原型到量产过渡中存在 NPI、DFM、采购、质量或合规痛点的证据。",
    "Adoption and category-dynamics signal for AI, digital manufacturing, and supply-chain tooling.": "关于 AI、数字化制造和供应链工具采用情况与品类动态的信号。",
    "Market-growth evidence for robotics end-markets that create more first-board manufacturing programs.": "机器人终端市场增长的证据，意味着会产生更多首板制造项目。",
    "Industry standards-body context for electronics manufacturing workflows.": "电子制造工作流的行业标准机构背景。",
    "Open-source substitute and interoperability evidence in the PCB design toolchain.": "PCB 设计工具链中的开源替代方案和互操作性证据。",
    "Official compliance or cybersecurity context likely to affect connected hardware releases.": "可能影响联网硬件发版的官方合规或网络安全背景。",
}


def translate(obj):
    if isinstance(obj, str):
        return TRANSLATIONS.get(obj, obj)
    if isinstance(obj, list):
        return [translate(item) for item in obj]
    if isinstance(obj, dict):
        return {k: translate(v) for k, v in obj.items()}
    return obj


def load_yaml(path: Path):
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def dump_yaml(path: Path, data):
    with path.open("w", encoding="utf-8") as f:
        yaml.safe_dump(
            data,
            f,
            allow_unicode=True,
            sort_keys=False,
            width=1000,
            default_flow_style=False,
        )


def schema_shape(obj):
    if isinstance(obj, dict):
        return {k: schema_shape(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [schema_shape(v) for v in obj]
    if obj is None:
        return None
    return type(obj).__name__


def verify_pair(src_path: Path, zh_path: Path):
    if not zh_path.exists():
        raise RuntimeError(f"missing output: {zh_path}")
    if zh_path.stat().st_size == 0:
        raise RuntimeError(f"empty output: {zh_path}")
    src = load_yaml(src_path)
    zh = load_yaml(zh_path)
    if schema_shape(src) != schema_shape(zh):
        raise RuntimeError(f"schema mismatch: {zh_path}")


def main():
    pairs = [
        ("idea.yaml", "idea.zh.yaml"),
        ("research.yaml", "research.zh.yaml"),
        ("business-plan.yaml", "business-plan.zh.yaml"),
        ("financial-model.yaml", "financial-model.zh.yaml"),
        ("index.yaml", "index.zh.yaml"),
    ]

    for src_name, zh_name in pairs:
        src_path = REPORT_DIR / src_name
        data = load_yaml(src_path)
        zh = translate(copy.deepcopy(data))
        dump_yaml(REPORT_DIR / zh_name, zh)

    for src_name, zh_name in pairs:
        verify_pair(REPORT_DIR / src_name, REPORT_DIR / zh_name)

    print("OK")


if __name__ == "__main__":
    main()
